services:
  - type: web
    name: e-blood-donation
    env: python
    rootDir: blood donation/django_backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
